### ISSUE TITLE
bitlbee 3.4.1?

### ISSUE THREAD

**Issue by tnguyen14** [kalbasit/docker-images#1]
Is your bitlbee image version 3.4.1?

**Comment by kalbasit** [comment]
this is embarrassing, sorry @tnguyen14 I had a problem with my Github and none of my repos are followed so I didn't get a notification :(. Did you find your answer?

**Comment by tnguyen14** [comment]
Hi, no problem. I don't think so, but I also don't use this anymore I believe. The page on docker hub https://hub.docker.com/r/kalbasit/bitlbee/ still does not have the version info.

**Comment by kalbasit** [comment]
@tnguyen14 I don't use it anymore either. However, if I do, it will be on quay instead of docker hub. https://quay.io/user/kalbasit
